"""add indexes

Revision ID: 5e6ade4b5abb
Revises: c0628cdcbd50
Create Date: 2026-06-23 22:49:46.519512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e6ade4b5abb'
down_revision: Union[str, Sequence[str], None] = 'c0628cdcbd50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_asset_last_seen', 'assets', ['last_seen'], unique=False)
    op.create_index('ix_asset_status', 'assets', ['status'], unique=False)
    op.create_index('ix_assets_tags', 'assets', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_tags', table_name='assets', postgresql_using='gin')
    op.drop_index('ix_asset_status', table_name='assets')
    op.drop_index('ix_asset_last_seen', table_name='assets')
    # ### end Alembic commands ###
