"""create assets and relationships tables

Revision ID: de53667445f6
Revises: 
Create Date: 2026-06-22 03:10:06.781456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'de53667445f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('type', sa.Enum('domain', 'subdomain', 'ip_address', 'service', 'certificate', 'technology', name='assettype'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'stale', 'archived', name='assetstatus'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'value', name='uq_asset_type_value')
    )
    op.create_index(op.f('ix_assets_status'), 'assets', ['status'], unique=False)
    op.create_index('ix_assets_tags', 'assets', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.create_index('ix_assets_value_trgm', 'assets', ['value'], unique=False, postgresql_using='gin', postgresql_ops={'value': 'gin_trgm_ops'})
    op.create_table('asset_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'relationship_type', name='uq_relationship_source_target_type')
    )
    op.create_index(op.f('ix_asset_relationships_source_id'), 'asset_relationships', ['source_id'], unique=False)
    op.create_index(op.f('ix_asset_relationships_target_id'), 'asset_relationships', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asset_relationships_target_id'), table_name='asset_relationships')
    op.drop_index(op.f('ix_asset_relationships_source_id'), table_name='asset_relationships')
    op.drop_table('asset_relationships')
    op.drop_index('ix_assets_value_trgm', table_name='assets', postgresql_using='gin', postgresql_ops={'value': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index('ix_assets_tags', table_name='assets', postgresql_using='gin')
    op.drop_index(op.f('ix_assets_status'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
